public enum TypeMSG {
        // OyenteCliente
    CONNECTION_MESSAGE, 
    USER_LIST_MESSAGE,
    FILE_REQUEST_MESSAGE,
    READY_CS_MESSAGE,
    CLOSE_CONNECTION_MESSAGE,
        
        // OyenteServidor
    CONNECTION_CONFIRMATION_MESSAGE,
    USER_LIST_CONFIRMATION_MESSAGE,
    FILE_REQUEST_MESSAGE,
    READY_SC_MESSAGE
}